### ISSUE TITLE
Comparison with `github.com/exaring/otelpgx`?

### ISSUE THREAD

**Issue by StevenACoffman** [pgx-contrib/pgxotel#12]
I am curious about the differences between this and `github.com/exaring/otelpgx`.

I currently use `github.com/exaring/otelpgx` with my `pgxpool`:
```
cfg, err := pgxpool.ParseConfig(connString)
if err != nil {
    return nil, fmt.Errorf("create connection pool: %w", err)
}

cfg.ConnConfig.Tracer = otelpgx.NewTracer()

conn, err := pgxpool.NewWithConfig(ctx, cfg)
if err != nil {
    return nil, fmt.Errorf("connect to database: %w", err)
}
```

**Comment by iamralch** [comment]
@StevenACoffman There is no much significant difference. It's up to you which one do you like. It looks like that github.com/exaring/otelpgx is much more flexible.
